FROM --platform=linux/amd64 public.ecr.aws/i6b2w2n6/op-geth:7.1.0

RUN apk update
RUN apk add --no-cache jq

COPY entrypoint.sh /entrypoint.sh

VOLUME ["/db"]

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
